// Code generated by protoc-gen-go.
// source: AgentConfig.proto
// DO NOT EDIT!

/*
Package org_glowroot_wire_api_model is a generated protocol buffer package.

It is generated from these files:
	AgentConfig.proto
	Aggregate.proto
	CollectorService.proto
	Common.proto
	DownstreamService.proto
	Profile.proto
	Trace.proto

It has these top-level messages:
	AgentConfig
	OldAggregatesByType
	OldTransactionAggregate
	Aggregate
	InitMessage
	InitResponse
	OldAggregateMessage
	AggregateStreamMessage
	AggregateResponseMessage
	GaugeValueMessage
	OldTraceMessage
	TraceStreamMessage
	LogMessage
	Environment
	HostInfo
	ProcessInfo
	JavaInfo
	AggregateStreamHeader
	OverallAggregate
	TransactionAggregate
	GaugeValue
	TraceStreamHeader
	LogEvent
	EmptyMessage
	Throwable
	StackTraceElement
	OptionalInt64
	OptionalInt32
	OptionalDouble
	CentralRequest
	AgentResponse
	Hello
	HelloAck
	AgentConfigUpdateRequest
	AgentConfigUpdateResponse
	ThreadDumpRequest
	ThreadDumpResponse
	JstackRequest
	JstackResponse
	AvailableDiskSpaceRequest
	AvailableDiskSpaceResponse
	HeapDumpRequest
	HeapDumpResponse
	HeapHistogramRequest
	HeapHistogramResponse
	GcRequest
	GcResponse
	MBeanDumpRequest
	MBeanDumpResponse
	MatchingMBeanObjectNamesRequest
	MatchingMBeanObjectNamesResponse
	MBeanMetaRequest
	MBeanMetaResponse
	SystemPropertiesRequest
	SystemPropertiesResponse
	CapabilitiesRequest
	CapabilitiesResponse
	GlobalMetaRequest
	GlobalMetaResponse
	PreloadClasspathCacheRequest
	PreloadClasspathCacheResponse
	MatchingClassNamesRequest
	MatchingClassNamesResponse
	MatchingMethodNamesRequest
	MatchingMethodNamesResponse
	MethodSignaturesRequest
	MethodSignaturesResponse
	ReweaveRequest
	ReweaveResponse
	HeaderRequest
	HeaderResponse
	EntriesRequest
	EntriesResponse
	MainThreadProfileRequest
	MainThreadProfileResponse
	AuxThreadProfileRequest
	AuxThreadProfileResponse
	FullTraceRequest
	FullTraceResponse
	UnknownRequestResponse
	ExceptionResponse
	ThreadDump
	HeapDumpFileInfo
	HeapHistogram
	MBeanDump
	MBeanMeta
	Capabilities
	Availability
	GlobalMeta
	MethodSignature
	Profile
	Trace
*/
package org_glowroot_wire_api_model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AgentConfig_AlertConfig_AlertKind int32

const (
	AgentConfig_AlertConfig_TRANSACTION AgentConfig_AlertConfig_AlertKind = 0
	AgentConfig_AlertConfig_GAUGE       AgentConfig_AlertConfig_AlertKind = 1
)

var AgentConfig_AlertConfig_AlertKind_name = map[int32]string{
	0: "TRANSACTION",
	1: "GAUGE",
}
var AgentConfig_AlertConfig_AlertKind_value = map[string]int32{
	"TRANSACTION": 0,
	"GAUGE":       1,
}

func (x AgentConfig_AlertConfig_AlertKind) String() string {
	return proto.EnumName(AgentConfig_AlertConfig_AlertKind_name, int32(x))
}
func (AgentConfig_AlertConfig_AlertKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 5, 0}
}

type AgentConfig_InstrumentationConfig_MethodModifier int32

const (
	AgentConfig_InstrumentationConfig_PUBLIC     AgentConfig_InstrumentationConfig_MethodModifier = 0
	AgentConfig_InstrumentationConfig_STATIC     AgentConfig_InstrumentationConfig_MethodModifier = 1
	AgentConfig_InstrumentationConfig_NOT_STATIC AgentConfig_InstrumentationConfig_MethodModifier = 2
)

var AgentConfig_InstrumentationConfig_MethodModifier_name = map[int32]string{
	0: "PUBLIC",
	1: "STATIC",
	2: "NOT_STATIC",
}
var AgentConfig_InstrumentationConfig_MethodModifier_value = map[string]int32{
	"PUBLIC":     0,
	"STATIC":     1,
	"NOT_STATIC": 2,
}

func (x AgentConfig_InstrumentationConfig_MethodModifier) String() string {
	return proto.EnumName(AgentConfig_InstrumentationConfig_MethodModifier_name, int32(x))
}
func (AgentConfig_InstrumentationConfig_MethodModifier) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 7, 0}
}

type AgentConfig_InstrumentationConfig_CaptureKind int32

const (
	AgentConfig_InstrumentationConfig_TRANSACTION AgentConfig_InstrumentationConfig_CaptureKind = 0
	AgentConfig_InstrumentationConfig_TRACE_ENTRY AgentConfig_InstrumentationConfig_CaptureKind = 1
	AgentConfig_InstrumentationConfig_TIMER       AgentConfig_InstrumentationConfig_CaptureKind = 2
	AgentConfig_InstrumentationConfig_OTHER       AgentConfig_InstrumentationConfig_CaptureKind = 3
)

var AgentConfig_InstrumentationConfig_CaptureKind_name = map[int32]string{
	0: "TRANSACTION",
	1: "TRACE_ENTRY",
	2: "TIMER",
	3: "OTHER",
}
var AgentConfig_InstrumentationConfig_CaptureKind_value = map[string]int32{
	"TRANSACTION": 0,
	"TRACE_ENTRY": 1,
	"TIMER":       2,
	"OTHER":       3,
}

func (x AgentConfig_InstrumentationConfig_CaptureKind) String() string {
	return proto.EnumName(AgentConfig_InstrumentationConfig_CaptureKind_name, int32(x))
}
func (AgentConfig_InstrumentationConfig_CaptureKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 7, 1}
}

type AgentConfig struct {
	AgentVersion          string                               `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion" json:"agent_version,omitempty"`
	TransactionConfig     *AgentConfig_TransactionConfig       `protobuf:"bytes,2,opt,name=transaction_config,json=transactionConfig" json:"transaction_config,omitempty"`
	UiConfig              *AgentConfig_UiConfig                `protobuf:"bytes,3,opt,name=ui_config,json=uiConfig" json:"ui_config,omitempty"`
	UserRecordingConfig   *AgentConfig_UserRecordingConfig     `protobuf:"bytes,4,opt,name=user_recording_config,json=userRecordingConfig" json:"user_recording_config,omitempty"`
	AdvancedConfig        *AgentConfig_AdvancedConfig          `protobuf:"bytes,5,opt,name=advanced_config,json=advancedConfig" json:"advanced_config,omitempty"`
	GaugeConfig           []*AgentConfig_GaugeConfig           `protobuf:"bytes,10,rep,name=gauge_config,json=gaugeConfig" json:"gauge_config,omitempty"`
	AlertConfig           []*AgentConfig_AlertConfig           `protobuf:"bytes,11,rep,name=alert_config,json=alertConfig" json:"alert_config,omitempty"`
	PluginConfig          []*AgentConfig_PluginConfig          `protobuf:"bytes,12,rep,name=plugin_config,json=pluginConfig" json:"plugin_config,omitempty"`
	InstrumentationConfig []*AgentConfig_InstrumentationConfig `protobuf:"bytes,13,rep,name=instrumentation_config,json=instrumentationConfig" json:"instrumentation_config,omitempty"`
}

func (m *AgentConfig) Reset()                    { *m = AgentConfig{} }
func (m *AgentConfig) String() string            { return proto.CompactTextString(m) }
func (*AgentConfig) ProtoMessage()               {}
func (*AgentConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AgentConfig) GetAgentVersion() string {
	if m != nil {
		return m.AgentVersion
	}
	return ""
}

func (m *AgentConfig) GetTransactionConfig() *AgentConfig_TransactionConfig {
	if m != nil {
		return m.TransactionConfig
	}
	return nil
}

func (m *AgentConfig) GetUiConfig() *AgentConfig_UiConfig {
	if m != nil {
		return m.UiConfig
	}
	return nil
}

func (m *AgentConfig) GetUserRecordingConfig() *AgentConfig_UserRecordingConfig {
	if m != nil {
		return m.UserRecordingConfig
	}
	return nil
}

func (m *AgentConfig) GetAdvancedConfig() *AgentConfig_AdvancedConfig {
	if m != nil {
		return m.AdvancedConfig
	}
	return nil
}

func (m *AgentConfig) GetGaugeConfig() []*AgentConfig_GaugeConfig {
	if m != nil {
		return m.GaugeConfig
	}
	return nil
}

func (m *AgentConfig) GetAlertConfig() []*AgentConfig_AlertConfig {
	if m != nil {
		return m.AlertConfig
	}
	return nil
}

func (m *AgentConfig) GetPluginConfig() []*AgentConfig_PluginConfig {
	if m != nil {
		return m.PluginConfig
	}
	return nil
}

func (m *AgentConfig) GetInstrumentationConfig() []*AgentConfig_InstrumentationConfig {
	if m != nil {
		return m.InstrumentationConfig
	}
	return nil
}

type AgentConfig_TransactionConfig struct {
	SlowThresholdMillis     *OptionalInt32 `protobuf:"bytes,1,opt,name=slow_threshold_millis,json=slowThresholdMillis" json:"slow_threshold_millis,omitempty"`
	ProfilingIntervalMillis *OptionalInt32 `protobuf:"bytes,2,opt,name=profiling_interval_millis,json=profilingIntervalMillis" json:"profiling_interval_millis,omitempty"`
	CaptureThreadStats      bool           `protobuf:"varint,3,opt,name=capture_thread_stats,json=captureThreadStats" json:"capture_thread_stats,omitempty"`
}

func (m *AgentConfig_TransactionConfig) Reset()         { *m = AgentConfig_TransactionConfig{} }
func (m *AgentConfig_TransactionConfig) String() string { return proto.CompactTextString(m) }
func (*AgentConfig_TransactionConfig) ProtoMessage()    {}
func (*AgentConfig_TransactionConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

func (m *AgentConfig_TransactionConfig) GetSlowThresholdMillis() *OptionalInt32 {
	if m != nil {
		return m.SlowThresholdMillis
	}
	return nil
}

func (m *AgentConfig_TransactionConfig) GetProfilingIntervalMillis() *OptionalInt32 {
	if m != nil {
		return m.ProfilingIntervalMillis
	}
	return nil
}

func (m *AgentConfig_TransactionConfig) GetCaptureThreadStats() bool {
	if m != nil {
		return m.CaptureThreadStats
	}
	return false
}

type AgentConfig_UiConfig struct {
	DefaultDisplayedTransactionType string    `protobuf:"bytes,1,opt,name=default_displayed_transaction_type,json=defaultDisplayedTransactionType" json:"default_displayed_transaction_type,omitempty"`
	DefaultDisplayedPercentile      []float64 `protobuf:"fixed64,2,rep,packed,name=default_displayed_percentile,json=defaultDisplayedPercentile" json:"default_displayed_percentile,omitempty"`
}

func (m *AgentConfig_UiConfig) Reset()                    { *m = AgentConfig_UiConfig{} }
func (m *AgentConfig_UiConfig) String() string            { return proto.CompactTextString(m) }
func (*AgentConfig_UiConfig) ProtoMessage()               {}
func (*AgentConfig_UiConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *AgentConfig_UiConfig) GetDefaultDisplayedTransactionType() string {
	if m != nil {
		return m.DefaultDisplayedTransactionType
	}
	return ""
}

func (m *AgentConfig_UiConfig) GetDefaultDisplayedPercentile() []float64 {
	if m != nil {
		return m.DefaultDisplayedPercentile
	}
	return nil
}

type AgentConfig_UserRecordingConfig struct {
	User                    []string       `protobuf:"bytes,1,rep,name=user" json:"user,omitempty"`
	ProfilingIntervalMillis *OptionalInt32 `protobuf:"bytes,2,opt,name=profiling_interval_millis,json=profilingIntervalMillis" json:"profiling_interval_millis,omitempty"`
}

func (m *AgentConfig_UserRecordingConfig) Reset()         { *m = AgentConfig_UserRecordingConfig{} }
func (m *AgentConfig_UserRecordingConfig) String() string { return proto.CompactTextString(m) }
func (*AgentConfig_UserRecordingConfig) ProtoMessage()    {}
func (*AgentConfig_UserRecordingConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 2}
}

func (m *AgentConfig_UserRecordingConfig) GetUser() []string {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AgentConfig_UserRecordingConfig) GetProfilingIntervalMillis() *OptionalInt32 {
	if m != nil {
		return m.ProfilingIntervalMillis
	}
	return nil
}

type AgentConfig_AdvancedConfig struct {
	WeavingTimer bool `protobuf:"varint,1,opt,name=weaving_timer,json=weavingTimer" json:"weaving_timer,omitempty"`
	// optionals used below due to non-zero default value
	ImmediatePartialStoreThresholdSeconds *OptionalInt32 `protobuf:"bytes,2,opt,name=immediate_partial_store_threshold_seconds,json=immediatePartialStoreThresholdSeconds" json:"immediate_partial_store_threshold_seconds,omitempty"`
	MaxAggregateTransactionsPerType       *OptionalInt32 `protobuf:"bytes,3,opt,name=max_aggregate_transactions_per_type,json=maxAggregateTransactionsPerType" json:"max_aggregate_transactions_per_type,omitempty"`
	MaxAggregateQueriesPerType            *OptionalInt32 `protobuf:"bytes,4,opt,name=max_aggregate_queries_per_type,json=maxAggregateQueriesPerType" json:"max_aggregate_queries_per_type,omitempty"`
	MaxAggregateServiceCallsPerType       *OptionalInt32 `protobuf:"bytes,5,opt,name=max_aggregate_service_calls_per_type,json=maxAggregateServiceCallsPerType" json:"max_aggregate_service_calls_per_type,omitempty"`
	MaxTraceEntriesPerTransaction         *OptionalInt32 `protobuf:"bytes,6,opt,name=max_trace_entries_per_transaction,json=maxTraceEntriesPerTransaction" json:"max_trace_entries_per_transaction,omitempty"`
	MaxStackTraceSamplesPerTransaction    *OptionalInt32 `protobuf:"bytes,7,opt,name=max_stack_trace_samples_per_transaction,json=maxStackTraceSamplesPerTransaction" json:"max_stack_trace_samples_per_transaction,omitempty"`
	MbeanGaugeNotFoundDelaySeconds        *OptionalInt32 `protobuf:"bytes,8,opt,name=mbean_gauge_not_found_delay_seconds,json=mbeanGaugeNotFoundDelaySeconds" json:"mbean_gauge_not_found_delay_seconds,omitempty"`
}

func (m *AgentConfig_AdvancedConfig) Reset()                    { *m = AgentConfig_AdvancedConfig{} }
func (m *AgentConfig_AdvancedConfig) String() string            { return proto.CompactTextString(m) }
func (*AgentConfig_AdvancedConfig) ProtoMessage()               {}
func (*AgentConfig_AdvancedConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 3} }

func (m *AgentConfig_AdvancedConfig) GetWeavingTimer() bool {
	if m != nil {
		return m.WeavingTimer
	}
	return false
}

func (m *AgentConfig_AdvancedConfig) GetImmediatePartialStoreThresholdSeconds() *OptionalInt32 {
	if m != nil {
		return m.ImmediatePartialStoreThresholdSeconds
	}
	return nil
}

func (m *AgentConfig_AdvancedConfig) GetMaxAggregateTransactionsPerType() *OptionalInt32 {
	if m != nil {
		return m.MaxAggregateTransactionsPerType
	}
	return nil
}

func (m *AgentConfig_AdvancedConfig) GetMaxAggregateQueriesPerType() *OptionalInt32 {
	if m != nil {
		return m.MaxAggregateQueriesPerType
	}
	return nil
}

func (m *AgentConfig_AdvancedConfig) GetMaxAggregateServiceCallsPerType() *OptionalInt32 {
	if m != nil {
		return m.MaxAggregateServiceCallsPerType
	}
	return nil
}

func (m *AgentConfig_AdvancedConfig) GetMaxTraceEntriesPerTransaction() *OptionalInt32 {
	if m != nil {
		return m.MaxTraceEntriesPerTransaction
	}
	return nil
}

func (m *AgentConfig_AdvancedConfig) GetMaxStackTraceSamplesPerTransaction() *OptionalInt32 {
	if m != nil {
		return m.MaxStackTraceSamplesPerTransaction
	}
	return nil
}

func (m *AgentConfig_AdvancedConfig) GetMbeanGaugeNotFoundDelaySeconds() *OptionalInt32 {
	if m != nil {
		return m.MbeanGaugeNotFoundDelaySeconds
	}
	return nil
}

type AgentConfig_GaugeConfig struct {
	MbeanObjectName string                        `protobuf:"bytes,1,opt,name=mbean_object_name,json=mbeanObjectName" json:"mbean_object_name,omitempty"`
	MbeanAttribute  []*AgentConfig_MBeanAttribute `protobuf:"bytes,2,rep,name=mbean_attribute,json=mbeanAttribute" json:"mbean_attribute,omitempty"`
}

func (m *AgentConfig_GaugeConfig) Reset()                    { *m = AgentConfig_GaugeConfig{} }
func (m *AgentConfig_GaugeConfig) String() string            { return proto.CompactTextString(m) }
func (*AgentConfig_GaugeConfig) ProtoMessage()               {}
func (*AgentConfig_GaugeConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 4} }

func (m *AgentConfig_GaugeConfig) GetMbeanObjectName() string {
	if m != nil {
		return m.MbeanObjectName
	}
	return ""
}

func (m *AgentConfig_GaugeConfig) GetMbeanAttribute() []*AgentConfig_MBeanAttribute {
	if m != nil {
		return m.MbeanAttribute
	}
	return nil
}

type AgentConfig_AlertConfig struct {
	Kind                       AgentConfig_AlertConfig_AlertKind `protobuf:"varint,1,opt,name=kind,enum=org_glowroot_wire_api_model.AgentConfig_AlertConfig_AlertKind" json:"kind,omitempty"`
	TransactionType            string                            `protobuf:"bytes,2,opt,name=transaction_type,json=transactionType" json:"transaction_type,omitempty"`
	TransactionPercentile      *OptionalDouble                   `protobuf:"bytes,3,opt,name=transaction_percentile,json=transactionPercentile" json:"transaction_percentile,omitempty"`
	TransactionThresholdMillis *OptionalInt32                    `protobuf:"bytes,4,opt,name=transaction_threshold_millis,json=transactionThresholdMillis" json:"transaction_threshold_millis,omitempty"`
	MinTransactionCount        *OptionalInt32                    `protobuf:"bytes,5,opt,name=min_transaction_count,json=minTransactionCount" json:"min_transaction_count,omitempty"`
	GaugeName                  string                            `protobuf:"bytes,6,opt,name=gauge_name,json=gaugeName" json:"gauge_name,omitempty"`
	GaugeThreshold             *OptionalDouble                   `protobuf:"bytes,7,opt,name=gauge_threshold,json=gaugeThreshold" json:"gauge_threshold,omitempty"`
	TimePeriodSeconds          int32                             `protobuf:"varint,8,opt,name=time_period_seconds,json=timePeriodSeconds" json:"time_period_seconds,omitempty"`
	EmailAddress               []string                          `protobuf:"bytes,9,rep,name=email_address,json=emailAddress" json:"email_address,omitempty"`
}

func (m *AgentConfig_AlertConfig) Reset()                    { *m = AgentConfig_AlertConfig{} }
func (m *AgentConfig_AlertConfig) String() string            { return proto.CompactTextString(m) }
func (*AgentConfig_AlertConfig) ProtoMessage()               {}
func (*AgentConfig_AlertConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 5} }

func (m *AgentConfig_AlertConfig) GetKind() AgentConfig_AlertConfig_AlertKind {
	if m != nil {
		return m.Kind
	}
	return AgentConfig_AlertConfig_TRANSACTION
}

func (m *AgentConfig_AlertConfig) GetTransactionType() string {
	if m != nil {
		return m.TransactionType
	}
	return ""
}

func (m *AgentConfig_AlertConfig) GetTransactionPercentile() *OptionalDouble {
	if m != nil {
		return m.TransactionPercentile
	}
	return nil
}

func (m *AgentConfig_AlertConfig) GetTransactionThresholdMillis() *OptionalInt32 {
	if m != nil {
		return m.TransactionThresholdMillis
	}
	return nil
}

func (m *AgentConfig_AlertConfig) GetMinTransactionCount() *OptionalInt32 {
	if m != nil {
		return m.MinTransactionCount
	}
	return nil
}

func (m *AgentConfig_AlertConfig) GetGaugeName() string {
	if m != nil {
		return m.GaugeName
	}
	return ""
}

func (m *AgentConfig_AlertConfig) GetGaugeThreshold() *OptionalDouble {
	if m != nil {
		return m.GaugeThreshold
	}
	return nil
}

func (m *AgentConfig_AlertConfig) GetTimePeriodSeconds() int32 {
	if m != nil {
		return m.TimePeriodSeconds
	}
	return 0
}

func (m *AgentConfig_AlertConfig) GetEmailAddress() []string {
	if m != nil {
		return m.EmailAddress
	}
	return nil
}

type AgentConfig_PluginConfig struct {
	Id       string                        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name     string                        `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Property []*AgentConfig_PluginProperty `protobuf:"bytes,3,rep,name=property" json:"property,omitempty"`
}

func (m *AgentConfig_PluginConfig) Reset()                    { *m = AgentConfig_PluginConfig{} }
func (m *AgentConfig_PluginConfig) String() string            { return proto.CompactTextString(m) }
func (*AgentConfig_PluginConfig) ProtoMessage()               {}
func (*AgentConfig_PluginConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 6} }

func (m *AgentConfig_PluginConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AgentConfig_PluginConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AgentConfig_PluginConfig) GetProperty() []*AgentConfig_PluginProperty {
	if m != nil {
		return m.Property
	}
	return nil
}

type AgentConfig_InstrumentationConfig struct {
	ClassName                      string                                             `protobuf:"bytes,1,opt,name=class_name,json=className" json:"class_name,omitempty"`
	ClassAnnotation                string                                             `protobuf:"bytes,2,opt,name=class_annotation,json=classAnnotation" json:"class_annotation,omitempty"`
	MethodDeclaringClassName       string                                             `protobuf:"bytes,3,opt,name=method_declaring_class_name,json=methodDeclaringClassName" json:"method_declaring_class_name,omitempty"`
	MethodName                     string                                             `protobuf:"bytes,4,opt,name=method_name,json=methodName" json:"method_name,omitempty"`
	MethodAnnotation               string                                             `protobuf:"bytes,5,opt,name=method_annotation,json=methodAnnotation" json:"method_annotation,omitempty"`
	MethodParameterType            []string                                           `protobuf:"bytes,6,rep,name=method_parameter_type,json=methodParameterType" json:"method_parameter_type,omitempty"`
	MethodReturnType               string                                             `protobuf:"bytes,7,opt,name=method_return_type,json=methodReturnType" json:"method_return_type,omitempty"`
	MethodModifier                 []AgentConfig_InstrumentationConfig_MethodModifier `protobuf:"varint,8,rep,packed,name=method_modifier,json=methodModifier,enum=org_glowroot_wire_api_model.AgentConfig_InstrumentationConfig_MethodModifier" json:"method_modifier,omitempty"`
	NestingGroup                   string                                             `protobuf:"bytes,9,opt,name=nesting_group,json=nestingGroup" json:"nesting_group,omitempty"`
	Priority                       int32                                              `protobuf:"varint,10,opt,name=priority" json:"priority,omitempty"`
	CaptureKind                    AgentConfig_InstrumentationConfig_CaptureKind      `protobuf:"varint,11,opt,name=capture_kind,json=captureKind,enum=org_glowroot_wire_api_model.AgentConfig_InstrumentationConfig_CaptureKind" json:"capture_kind,omitempty"`
	TimerName                      string                                             `protobuf:"bytes,12,opt,name=timer_name,json=timerName" json:"timer_name,omitempty"`
	TraceEntryMessageTemplate      string                                             `protobuf:"bytes,13,opt,name=trace_entry_message_template,json=traceEntryMessageTemplate" json:"trace_entry_message_template,omitempty"`
	TraceEntryStackThresholdMillis *OptionalInt32                                     `protobuf:"bytes,14,opt,name=trace_entry_stack_threshold_millis,json=traceEntryStackThresholdMillis" json:"trace_entry_stack_threshold_millis,omitempty"`
	TraceEntryCaptureSelfNested    bool                                               `protobuf:"varint,15,opt,name=trace_entry_capture_self_nested,json=traceEntryCaptureSelfNested" json:"trace_entry_capture_self_nested,omitempty"`
	TransactionType                string                                             `protobuf:"bytes,16,opt,name=transaction_type,json=transactionType" json:"transaction_type,omitempty"`
	TransactionNameTemplate        string                                             `protobuf:"bytes,17,opt,name=transaction_name_template,json=transactionNameTemplate" json:"transaction_name_template,omitempty"`
	TransactionUserTemplate        string                                             `protobuf:"bytes,18,opt,name=transaction_user_template,json=transactionUserTemplate" json:"transaction_user_template,omitempty"`
	TransactionAttributeTemplates  map[string]string                                  `protobuf:"bytes,19,rep,name=transaction_attribute_templates,json=transactionAttributeTemplates" json:"transaction_attribute_templates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TransactionSlowThresholdMillis *OptionalInt32                                     `protobuf:"bytes,20,opt,name=transaction_slow_threshold_millis,json=transactionSlowThresholdMillis" json:"transaction_slow_threshold_millis,omitempty"`
	EnabledProperty                string                                             `protobuf:"bytes,21,opt,name=enabled_property,json=enabledProperty" json:"enabled_property,omitempty"`
	TraceEntryEnabledProperty      string                                             `protobuf:"bytes,22,opt,name=trace_entry_enabled_property,json=traceEntryEnabledProperty" json:"trace_entry_enabled_property,omitempty"`
}

func (m *AgentConfig_InstrumentationConfig) Reset()         { *m = AgentConfig_InstrumentationConfig{} }
func (m *AgentConfig_InstrumentationConfig) String() string { return proto.CompactTextString(m) }
func (*AgentConfig_InstrumentationConfig) ProtoMessage()    {}
func (*AgentConfig_InstrumentationConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 7}
}

func (m *AgentConfig_InstrumentationConfig) GetClassName() string {
	if m != nil {
		return m.ClassName
	}
	return ""
}

func (m *AgentConfig_InstrumentationConfig) GetClassAnnotation() string {
	if m != nil {
		return m.ClassAnnotation
	}
	return ""
}

func (m *AgentConfig_InstrumentationConfig) GetMethodDeclaringClassName() string {
	if m != nil {
		return m.MethodDeclaringClassName
	}
	return ""
}

func (m *AgentConfig_InstrumentationConfig) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *AgentConfig_InstrumentationConfig) GetMethodAnnotation() string {
	if m != nil {
		return m.MethodAnnotation
	}
	return ""
}

func (m *AgentConfig_InstrumentationConfig) GetMethodParameterType() []string {
	if m != nil {
		return m.MethodParameterType
	}
	return nil
}

func (m *AgentConfig_InstrumentationConfig) GetMethodReturnType() string {
	if m != nil {
		return m.MethodReturnType
	}
	return ""
}

func (m *AgentConfig_InstrumentationConfig) GetMethodModifier() []AgentConfig_InstrumentationConfig_MethodModifier {
	if m != nil {
		return m.MethodModifier
	}
	return nil
}

func (m *AgentConfig_InstrumentationConfig) GetNestingGroup() string {
	if m != nil {
		return m.NestingGroup
	}
	return ""
}

func (m *AgentConfig_InstrumentationConfig) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *AgentConfig_InstrumentationConfig) GetCaptureKind() AgentConfig_InstrumentationConfig_CaptureKind {
	if m != nil {
		return m.CaptureKind
	}
	return AgentConfig_InstrumentationConfig_TRANSACTION
}

func (m *AgentConfig_InstrumentationConfig) GetTimerName() string {
	if m != nil {
		return m.TimerName
	}
	return ""
}

func (m *AgentConfig_InstrumentationConfig) GetTraceEntryMessageTemplate() string {
	if m != nil {
		return m.TraceEntryMessageTemplate
	}
	return ""
}

func (m *AgentConfig_InstrumentationConfig) GetTraceEntryStackThresholdMillis() *OptionalInt32 {
	if m != nil {
		return m.TraceEntryStackThresholdMillis
	}
	return nil
}

func (m *AgentConfig_InstrumentationConfig) GetTraceEntryCaptureSelfNested() bool {
	if m != nil {
		return m.TraceEntryCaptureSelfNested
	}
	return false
}

func (m *AgentConfig_InstrumentationConfig) GetTransactionType() string {
	if m != nil {
		return m.TransactionType
	}
	return ""
}

func (m *AgentConfig_InstrumentationConfig) GetTransactionNameTemplate() string {
	if m != nil {
		return m.TransactionNameTemplate
	}
	return ""
}

func (m *AgentConfig_InstrumentationConfig) GetTransactionUserTemplate() string {
	if m != nil {
		return m.TransactionUserTemplate
	}
	return ""
}

func (m *AgentConfig_InstrumentationConfig) GetTransactionAttributeTemplates() map[string]string {
	if m != nil {
		return m.TransactionAttributeTemplates
	}
	return nil
}

func (m *AgentConfig_InstrumentationConfig) GetTransactionSlowThresholdMillis() *OptionalInt32 {
	if m != nil {
		return m.TransactionSlowThresholdMillis
	}
	return nil
}

func (m *AgentConfig_InstrumentationConfig) GetEnabledProperty() string {
	if m != nil {
		return m.EnabledProperty
	}
	return ""
}

func (m *AgentConfig_InstrumentationConfig) GetTraceEntryEnabledProperty() string {
	if m != nil {
		return m.TraceEntryEnabledProperty
	}
	return ""
}

type AgentConfig_MBeanAttribute struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Counter bool   `protobuf:"varint,2,opt,name=counter" json:"counter,omitempty"`
}

func (m *AgentConfig_MBeanAttribute) Reset()                    { *m = AgentConfig_MBeanAttribute{} }
func (m *AgentConfig_MBeanAttribute) String() string            { return proto.CompactTextString(m) }
func (*AgentConfig_MBeanAttribute) ProtoMessage()               {}
func (*AgentConfig_MBeanAttribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 8} }

func (m *AgentConfig_MBeanAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AgentConfig_MBeanAttribute) GetCounter() bool {
	if m != nil {
		return m.Counter
	}
	return false
}

type AgentConfig_PluginProperty struct {
	Name          string                            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value         *AgentConfig_PluginProperty_Value `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Default       *AgentConfig_PluginProperty_Value `protobuf:"bytes,3,opt,name=default" json:"default,omitempty"`
	Label         string                            `protobuf:"bytes,4,opt,name=label" json:"label,omitempty"`
	CheckboxLabel string                            `protobuf:"bytes,5,opt,name=checkbox_label,json=checkboxLabel" json:"checkbox_label,omitempty"`
	Description   string                            `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
}

func (m *AgentConfig_PluginProperty) Reset()                    { *m = AgentConfig_PluginProperty{} }
func (m *AgentConfig_PluginProperty) String() string            { return proto.CompactTextString(m) }
func (*AgentConfig_PluginProperty) ProtoMessage()               {}
func (*AgentConfig_PluginProperty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 9} }

func (m *AgentConfig_PluginProperty) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AgentConfig_PluginProperty) GetValue() *AgentConfig_PluginProperty_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *AgentConfig_PluginProperty) GetDefault() *AgentConfig_PluginProperty_Value {
	if m != nil {
		return m.Default
	}
	return nil
}

func (m *AgentConfig_PluginProperty) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *AgentConfig_PluginProperty) GetCheckboxLabel() string {
	if m != nil {
		return m.CheckboxLabel
	}
	return ""
}

func (m *AgentConfig_PluginProperty) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type AgentConfig_PluginProperty_Value struct {
	// Types that are valid to be assigned to Val:
	//	*AgentConfig_PluginProperty_Value_Bval
	//	*AgentConfig_PluginProperty_Value_DvalNull
	//	*AgentConfig_PluginProperty_Value_Dval
	//	*AgentConfig_PluginProperty_Value_Sval
	Val isAgentConfig_PluginProperty_Value_Val `protobuf_oneof:"val"`
}

func (m *AgentConfig_PluginProperty_Value) Reset()         { *m = AgentConfig_PluginProperty_Value{} }
func (m *AgentConfig_PluginProperty_Value) String() string { return proto.CompactTextString(m) }
func (*AgentConfig_PluginProperty_Value) ProtoMessage()    {}
func (*AgentConfig_PluginProperty_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 9, 0}
}

type isAgentConfig_PluginProperty_Value_Val interface {
	isAgentConfig_PluginProperty_Value_Val()
}

type AgentConfig_PluginProperty_Value_Bval struct {
	Bval bool `protobuf:"varint,1,opt,name=bval,oneof"`
}
type AgentConfig_PluginProperty_Value_DvalNull struct {
	DvalNull bool `protobuf:"varint,2,opt,name=dval_null,json=dvalNull,oneof"`
}
type AgentConfig_PluginProperty_Value_Dval struct {
	Dval float64 `protobuf:"fixed64,3,opt,name=dval,oneof"`
}
type AgentConfig_PluginProperty_Value_Sval struct {
	Sval string `protobuf:"bytes,4,opt,name=sval,oneof"`
}

func (*AgentConfig_PluginProperty_Value_Bval) isAgentConfig_PluginProperty_Value_Val()     {}
func (*AgentConfig_PluginProperty_Value_DvalNull) isAgentConfig_PluginProperty_Value_Val() {}
func (*AgentConfig_PluginProperty_Value_Dval) isAgentConfig_PluginProperty_Value_Val()     {}
func (*AgentConfig_PluginProperty_Value_Sval) isAgentConfig_PluginProperty_Value_Val()     {}

func (m *AgentConfig_PluginProperty_Value) GetVal() isAgentConfig_PluginProperty_Value_Val {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *AgentConfig_PluginProperty_Value) GetBval() bool {
	if x, ok := m.GetVal().(*AgentConfig_PluginProperty_Value_Bval); ok {
		return x.Bval
	}
	return false
}

func (m *AgentConfig_PluginProperty_Value) GetDvalNull() bool {
	if x, ok := m.GetVal().(*AgentConfig_PluginProperty_Value_DvalNull); ok {
		return x.DvalNull
	}
	return false
}

func (m *AgentConfig_PluginProperty_Value) GetDval() float64 {
	if x, ok := m.GetVal().(*AgentConfig_PluginProperty_Value_Dval); ok {
		return x.Dval
	}
	return 0
}

func (m *AgentConfig_PluginProperty_Value) GetSval() string {
	if x, ok := m.GetVal().(*AgentConfig_PluginProperty_Value_Sval); ok {
		return x.Sval
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AgentConfig_PluginProperty_Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _AgentConfig_PluginProperty_Value_OneofMarshaler, _AgentConfig_PluginProperty_Value_OneofUnmarshaler, _AgentConfig_PluginProperty_Value_OneofSizer, []interface{}{
		(*AgentConfig_PluginProperty_Value_Bval)(nil),
		(*AgentConfig_PluginProperty_Value_DvalNull)(nil),
		(*AgentConfig_PluginProperty_Value_Dval)(nil),
		(*AgentConfig_PluginProperty_Value_Sval)(nil),
	}
}

func _AgentConfig_PluginProperty_Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*AgentConfig_PluginProperty_Value)
	// val
	switch x := m.Val.(type) {
	case *AgentConfig_PluginProperty_Value_Bval:
		t := uint64(0)
		if x.Bval {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *AgentConfig_PluginProperty_Value_DvalNull:
		t := uint64(0)
		if x.DvalNull {
			t = 1
		}
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *AgentConfig_PluginProperty_Value_Dval:
		b.EncodeVarint(3<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.Dval))
	case *AgentConfig_PluginProperty_Value_Sval:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Sval)
	case nil:
	default:
		return fmt.Errorf("AgentConfig_PluginProperty_Value.Val has unexpected type %T", x)
	}
	return nil
}

func _AgentConfig_PluginProperty_Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*AgentConfig_PluginProperty_Value)
	switch tag {
	case 1: // val.bval
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Val = &AgentConfig_PluginProperty_Value_Bval{x != 0}
		return true, err
	case 2: // val.dval_null
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Val = &AgentConfig_PluginProperty_Value_DvalNull{x != 0}
		return true, err
	case 3: // val.dval
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Val = &AgentConfig_PluginProperty_Value_Dval{math.Float64frombits(x)}
		return true, err
	case 4: // val.sval
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Val = &AgentConfig_PluginProperty_Value_Sval{x}
		return true, err
	default:
		return false, nil
	}
}

func _AgentConfig_PluginProperty_Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*AgentConfig_PluginProperty_Value)
	// val
	switch x := m.Val.(type) {
	case *AgentConfig_PluginProperty_Value_Bval:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += 1
	case *AgentConfig_PluginProperty_Value_DvalNull:
		n += proto.SizeVarint(2<<3 | proto.WireVarint)
		n += 1
	case *AgentConfig_PluginProperty_Value_Dval:
		n += proto.SizeVarint(3<<3 | proto.WireFixed64)
		n += 8
	case *AgentConfig_PluginProperty_Value_Sval:
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Sval)))
		n += len(x.Sval)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*AgentConfig)(nil), "org_glowroot_wire_api_model.AgentConfig")
	proto.RegisterType((*AgentConfig_TransactionConfig)(nil), "org_glowroot_wire_api_model.AgentConfig.TransactionConfig")
	proto.RegisterType((*AgentConfig_UiConfig)(nil), "org_glowroot_wire_api_model.AgentConfig.UiConfig")
	proto.RegisterType((*AgentConfig_UserRecordingConfig)(nil), "org_glowroot_wire_api_model.AgentConfig.UserRecordingConfig")
	proto.RegisterType((*AgentConfig_AdvancedConfig)(nil), "org_glowroot_wire_api_model.AgentConfig.AdvancedConfig")
	proto.RegisterType((*AgentConfig_GaugeConfig)(nil), "org_glowroot_wire_api_model.AgentConfig.GaugeConfig")
	proto.RegisterType((*AgentConfig_AlertConfig)(nil), "org_glowroot_wire_api_model.AgentConfig.AlertConfig")
	proto.RegisterType((*AgentConfig_PluginConfig)(nil), "org_glowroot_wire_api_model.AgentConfig.PluginConfig")
	proto.RegisterType((*AgentConfig_InstrumentationConfig)(nil), "org_glowroot_wire_api_model.AgentConfig.InstrumentationConfig")
	proto.RegisterType((*AgentConfig_MBeanAttribute)(nil), "org_glowroot_wire_api_model.AgentConfig.MBeanAttribute")
	proto.RegisterType((*AgentConfig_PluginProperty)(nil), "org_glowroot_wire_api_model.AgentConfig.PluginProperty")
	proto.RegisterType((*AgentConfig_PluginProperty_Value)(nil), "org_glowroot_wire_api_model.AgentConfig.PluginProperty.Value")
	proto.RegisterEnum("org_glowroot_wire_api_model.AgentConfig_AlertConfig_AlertKind", AgentConfig_AlertConfig_AlertKind_name, AgentConfig_AlertConfig_AlertKind_value)
	proto.RegisterEnum("org_glowroot_wire_api_model.AgentConfig_InstrumentationConfig_MethodModifier", AgentConfig_InstrumentationConfig_MethodModifier_name, AgentConfig_InstrumentationConfig_MethodModifier_value)
	proto.RegisterEnum("org_glowroot_wire_api_model.AgentConfig_InstrumentationConfig_CaptureKind", AgentConfig_InstrumentationConfig_CaptureKind_name, AgentConfig_InstrumentationConfig_CaptureKind_value)
}

func init() { proto.RegisterFile("AgentConfig.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1850 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x58, 0xcd, 0x73, 0x1b, 0xb7,
	0x15, 0x37, 0x49, 0x7d, 0xf1, 0x91, 0xa2, 0x28, 0xc8, 0x72, 0x68, 0x3a, 0x8a, 0x15, 0xb9, 0x99,
	0xc8, 0x4e, 0x87, 0xd3, 0x2a, 0xed, 0x34, 0xe3, 0x69, 0xd2, 0xd2, 0x92, 0x6a, 0xab, 0x89, 0x3e,
	0xba, 0xa4, 0x93, 0x69, 0x0f, 0xd9, 0x82, 0xbb, 0x10, 0x8d, 0x1a, 0xfb, 0x51, 0x2c, 0x56, 0x12,
	0x4f, 0xbd, 0x74, 0xa6, 0xa7, 0x1e, 0x72, 0xec, 0xf8, 0xd6, 0x5b, 0x8f, 0xfd, 0xf3, 0x7a, 0xeb,
	0xe0, 0x01, 0xbb, 0x5c, 0x52, 0x1c, 0x57, 0x94, 0x66, 0x7a, 0xe2, 0xe2, 0xe1, 0xbd, 0xdf, 0x0f,
	0x78, 0x78, 0x1f, 0x00, 0x61, 0xbd, 0x3b, 0x64, 0xa1, 0xda, 0x8f, 0xc2, 0x73, 0x3e, 0xec, 0xc4,
	0x32, 0x52, 0x11, 0x79, 0x14, 0xc9, 0xa1, 0x3b, 0x14, 0xd1, 0xa5, 0x8c, 0x22, 0xe5, 0x5e, 0x72,
	0xc9, 0x5c, 0x1a, 0x73, 0x37, 0x88, 0x7c, 0x26, 0xda, 0xf5, 0xfd, 0x28, 0x08, 0xa2, 0xd0, 0xa8,
	0xee, 0xfc, 0xe7, 0x19, 0xd4, 0x0a, 0x00, 0xe4, 0x09, 0xac, 0x52, 0x3d, 0x74, 0x2f, 0x98, 0x4c,
	0x78, 0x14, 0xb6, 0x4a, 0xdb, 0xa5, 0xdd, 0xaa, 0x53, 0x47, 0xe1, 0xb7, 0x46, 0x46, 0x38, 0x10,
	0x25, 0x69, 0x98, 0x50, 0x4f, 0xf1, 0x28, 0x74, 0x3d, 0x34, 0x6d, 0x95, 0xb7, 0x4b, 0xbb, 0xb5,
	0xbd, 0xe7, 0x9d, 0xf7, 0x90, 0x77, 0x8a, 0x6b, 0xed, 0x8f, 0x21, 0x8c, 0xc4, 0x59, 0x57, 0xd3,
	0x22, 0x72, 0x02, 0xd5, 0x94, 0x67, 0x0c, 0x15, 0x64, 0xf8, 0xe9, 0x8d, 0x19, 0x5e, 0x73, 0x0b,
	0xbc, 0x92, 0xda, 0x2f, 0x12, 0xc3, 0x66, 0x9a, 0x30, 0xe9, 0x4a, 0xe6, 0x45, 0xd2, 0xe7, 0xe1,
	0x30, 0xc3, 0x5e, 0x40, 0xec, 0x5f, 0xde, 0x1c, 0x3b, 0x61, 0xd2, 0xc9, 0x40, 0x2c, 0xcd, 0x46,
	0x7a, 0x5d, 0x48, 0xfe, 0x08, 0x6b, 0xd4, 0xbf, 0xa0, 0xa1, 0xc7, 0xfc, 0x8c, 0x6b, 0x11, 0xb9,
	0x7e, 0x71, 0x63, 0xae, 0xae, 0xb5, 0xb7, 0x34, 0x0d, 0x3a, 0x31, 0x26, 0xdf, 0x41, 0x7d, 0x48,
	0xd3, 0x21, 0xcb, 0xe0, 0x61, 0xbb, 0xb2, 0x5b, 0xdb, 0xfb, 0xd9, 0x8d, 0xe1, 0x5f, 0x6a, 0x63,
	0x8b, 0x5d, 0x1b, 0x8e, 0x07, 0x1a, 0x98, 0x0a, 0x26, 0x55, 0x06, 0x5c, 0x9b, 0x13, 0xb8, 0xab,
	0x8d, 0x33, 0x60, 0x3a, 0x1e, 0x90, 0x3f, 0xc0, 0x6a, 0x2c, 0xd2, 0x21, 0xcf, 0x63, 0xa7, 0x8e,
	0xc8, 0x3f, 0xbf, 0x31, 0xf2, 0x19, 0x5a, 0x5b, 0xe8, 0x7a, 0x5c, 0x18, 0x91, 0x14, 0x1e, 0xf0,
	0x30, 0x51, 0x32, 0x0d, 0x58, 0xa8, 0x68, 0x31, 0x40, 0x57, 0x91, 0xe4, 0xab, 0x1b, 0x93, 0x1c,
	0x4d, 0xc2, 0x58, 0xb6, 0x4d, 0x3e, 0x4b, 0xdc, 0xfe, 0x7b, 0x19, 0xd6, 0xaf, 0x45, 0x34, 0xf9,
	0x1e, 0x36, 0x13, 0x11, 0x5d, 0xba, 0xea, 0x8d, 0x64, 0xc9, 0x9b, 0x48, 0xf8, 0x6e, 0xc0, 0x85,
	0xe0, 0x09, 0xa6, 0x55, 0x6d, 0xef, 0xd9, 0x7b, 0xd7, 0x72, 0x1a, 0x6b, 0x24, 0x2a, 0x8e, 0x42,
	0xf5, 0xf9, 0x9e, 0xb3, 0xa1, 0x81, 0xfa, 0x19, 0xce, 0x31, 0xc2, 0x90, 0x73, 0x78, 0x18, 0xcb,
	0xe8, 0x9c, 0x0b, 0x1d, 0xc9, 0x3c, 0x54, 0x4c, 0x5e, 0x50, 0x91, 0x71, 0x94, 0xe7, 0xe6, 0xf8,
	0x20, 0x07, 0x3b, 0xb2, 0x58, 0x96, 0xe7, 0x27, 0x70, 0xdf, 0xa3, 0xb1, 0x4a, 0x25, 0xc3, 0xad,
	0x50, 0xdf, 0x4d, 0x14, 0x55, 0x09, 0x66, 0xe4, 0x8a, 0x43, 0xec, 0x5c, 0x1f, 0xa7, 0x7a, 0x7a,
	0xa6, 0xfd, 0x8f, 0x12, 0xac, 0x64, 0xf9, 0x47, 0xbe, 0x86, 0x1d, 0x9f, 0x9d, 0xd3, 0x54, 0x28,
	0xd7, 0xe7, 0x49, 0x2c, 0xe8, 0x88, 0xf9, 0x6e, 0xb1, 0x84, 0xa8, 0x51, 0xcc, 0x6c, 0xa9, 0x79,
	0x6c, 0x35, 0x0f, 0x32, 0xc5, 0x82, 0x57, 0xfb, 0xa3, 0x98, 0x91, 0x5f, 0xc3, 0x87, 0xd7, 0xc1,
	0x62, 0x26, 0x3d, 0x16, 0x2a, 0x2e, 0x58, 0xab, 0xbc, 0x5d, 0xd9, 0x2d, 0x39, 0xed, 0x69, 0x98,
	0xb3, 0x5c, 0xa3, 0xfd, 0x43, 0x09, 0x36, 0x66, 0xe4, 0x2f, 0x21, 0xb0, 0xa0, 0x33, 0xb8, 0x55,
	0xda, 0xae, 0xec, 0x56, 0x1d, 0xfc, 0xfe, 0x7f, 0x79, 0xb8, 0xfd, 0xc3, 0x32, 0x34, 0x26, 0xf3,
	0x5c, 0xd7, 0xe2, 0x4b, 0x46, 0x2f, 0x34, 0xb1, 0xe2, 0x01, 0xae, 0x4b, 0x7b, 0xbb, 0x6e, 0x85,
	0x7d, 0x2d, 0x23, 0x7f, 0x2d, 0xc1, 0x53, 0x1e, 0x04, 0xcc, 0xe7, 0x54, 0x31, 0x37, 0xa6, 0x52,
	0x71, 0x2a, 0xdc, 0x44, 0x45, 0xf6, 0xa8, 0x4c, 0xd4, 0x25, 0xcc, 0x8b, 0x42, 0xff, 0x36, 0x0b,
	0xfe, 0x24, 0x07, 0x3f, 0x33, 0xd8, 0x3d, 0x0d, 0x9d, 0xc7, 0x61, 0xcf, 0x00, 0x93, 0x2b, 0x78,
	0x12, 0xd0, 0x2b, 0x97, 0x0e, 0x87, 0x92, 0x0d, 0xf5, 0x4a, 0x0a, 0xa7, 0x9b, 0xe8, 0xd3, 0x31,
	0x47, 0x5c, 0x99, 0x9b, 0xff, 0x71, 0x40, 0xaf, 0xba, 0x19, 0x6a, 0x21, 0x14, 0x92, 0x33, 0x26,
	0x31, 0x1c, 0x42, 0xf8, 0x68, 0x92, 0xf9, 0xcf, 0x29, 0x93, 0x9c, 0x15, 0x48, 0x17, 0xe6, 0x26,
	0x6d, 0x17, 0x49, 0x7f, 0x67, 0xf0, 0x32, 0xbe, 0x11, 0xfc, 0x68, 0x92, 0x2f, 0x61, 0xf2, 0x82,
	0x7b, 0xcc, 0xf5, 0xa8, 0x10, 0x05, 0xd6, 0xc5, 0xbb, 0x6d, 0xb5, 0x67, 0x50, 0xf7, 0x35, 0x68,
	0x46, 0xad, 0xe0, 0x63, 0x4d, 0xad, 0x24, 0xf5, 0x98, 0xcb, 0x42, 0x35, 0xde, 0xe6, 0xd8, 0x2f,
	0xad, 0xa5, 0xb9, 0x79, 0xb7, 0x02, 0x7a, 0xd5, 0xd7, 0x98, 0x87, 0x06, 0x52, 0xd3, 0x8d, 0x01,
	0xc9, 0x5f, 0xe0, 0x53, 0xcd, 0x9a, 0x28, 0xea, 0xbd, 0xb5, 0xdc, 0x09, 0x0d, 0x62, 0x31, 0x83,
	0x7b, 0x79, 0x6e, 0xee, 0x9d, 0x80, 0x5e, 0xf5, 0x34, 0x32, 0x2e, 0xa0, 0x67, 0x70, 0xa7, 0x16,
	0x70, 0x09, 0x4f, 0x82, 0x01, 0xa3, 0xa1, 0x6b, 0xba, 0x5c, 0x18, 0x29, 0xf7, 0x3c, 0x4a, 0x43,
	0xdf, 0xf5, 0x99, 0xa0, 0xa3, 0x3c, 0xb6, 0x57, 0xe6, 0x26, 0xff, 0x08, 0x61, 0xb1, 0xfd, 0x9d,
	0x44, 0xea, 0x37, 0x1a, 0xf3, 0x40, 0x43, 0xda, 0xa0, 0x6e, 0xbf, 0x2b, 0x41, 0xad, 0xd0, 0x1c,
	0xc9, 0x33, 0x58, 0x37, 0x0b, 0x89, 0x06, 0x7f, 0x62, 0x9e, 0x72, 0x43, 0x1a, 0x64, 0x55, 0x6b,
	0x0d, 0x27, 0x4e, 0x51, 0x7e, 0x42, 0x03, 0xa6, 0xdb, 0xbe, 0xd1, 0xa5, 0x4a, 0x49, 0x3e, 0x48,
	0x95, 0x29, 0x4c, 0xf3, 0xb4, 0xfd, 0xe3, 0x17, 0x8c, 0x86, 0xdd, 0xcc, 0xdc, 0x69, 0x20, 0x5e,
	0x3e, 0x6e, 0xff, 0x7b, 0x11, 0x6a, 0x85, 0x0e, 0x4b, 0x1c, 0x58, 0x78, 0xcb, 0x43, 0x1f, 0x17,
	0xd4, 0x98, 0xa3, 0xcd, 0x15, 0x30, 0xcc, 0xf7, 0xd7, 0x3c, 0xf4, 0x1d, 0xc4, 0x22, 0x4f, 0xa1,
	0x79, 0xad, 0x4c, 0x97, 0xcd, 0x86, 0xd5, 0x54, 0x59, 0x1e, 0xc0, 0x83, 0xa2, 0x6a, 0xa1, 0x20,
	0x9b, 0xa4, 0xff, 0xec, 0x46, 0x07, 0x73, 0x10, 0xa5, 0x03, 0xc1, 0x9c, 0xcd, 0x02, 0xd4, 0xb8,
	0x70, 0x13, 0x01, 0x1f, 0x4e, 0x2c, 0x67, 0xba, 0xab, 0xde, 0x22, 0xd3, 0x8b, 0xdb, 0x98, 0x6a,
	0xae, 0xdf, 0xc3, 0x66, 0xc0, 0x43, 0x77, 0xf2, 0xaa, 0x9b, 0x86, 0xea, 0x16, 0xa9, 0xbd, 0x11,
	0xf0, 0x70, 0xe2, 0x76, 0x90, 0x86, 0x8a, 0x6c, 0x01, 0xd8, 0x88, 0xd6, 0x71, 0xb4, 0x84, 0x6e,
	0xad, 0xa2, 0x04, 0x23, 0xa8, 0x0f, 0x6b, 0x66, 0x3a, 0xdf, 0xa6, 0xcd, 0xaf, 0xb9, 0x3c, 0xd9,
	0x40, 0x8c, 0x7c, 0x6b, 0xa4, 0x03, 0x1b, 0xba, 0x99, 0xe8, 0xf3, 0xe1, 0x91, 0x3f, 0x91, 0x3c,
	0x8b, 0xce, 0xba, 0x9e, 0x3a, 0xc3, 0x99, 0xac, 0xb0, 0x3f, 0x81, 0x55, 0x16, 0x50, 0x2e, 0x5c,
	0xea, 0xfb, 0x92, 0x25, 0x49, 0xab, 0x8a, 0xcd, 0xb1, 0x8e, 0xc2, 0xae, 0x91, 0xed, 0x7c, 0x0a,
	0xd5, 0x3c, 0x72, 0xc8, 0x1a, 0xd4, 0xfa, 0x4e, 0xf7, 0xa4, 0xd7, 0xdd, 0xef, 0x1f, 0x9d, 0x9e,
	0x34, 0xef, 0x91, 0x2a, 0x2c, 0xbe, 0xec, 0xbe, 0x7e, 0x79, 0xd8, 0x2c, 0xb5, 0xff, 0x56, 0x82,
	0x7a, 0xf1, 0xee, 0x46, 0x1a, 0x50, 0xe6, 0xbe, 0xcd, 0xa1, 0x32, 0xf7, 0x75, 0x0b, 0x46, 0x6f,
	0x98, 0x20, 0xc3, 0x6f, 0xd2, 0x83, 0x95, 0x58, 0x46, 0x31, 0x93, 0x6a, 0xd4, 0xaa, 0xcc, 0x99,
	0x43, 0x86, 0xec, 0xcc, 0x9a, 0x3b, 0x39, 0x50, 0xfb, 0xdd, 0x2a, 0x6c, 0xce, 0xbc, 0xe0, 0xe9,
	0x63, 0xf1, 0x04, 0x4d, 0x92, 0x62, 0x7a, 0x57, 0x51, 0x82, 0xc7, 0xf2, 0x14, 0x9a, 0x66, 0x9a,
	0x86, 0x61, 0x64, 0x0c, 0xb3, 0x94, 0x40, 0x79, 0x37, 0x17, 0x93, 0x2f, 0xe1, 0x51, 0xc0, 0xd4,
	0x9b, 0x48, 0x57, 0x2a, 0x4f, 0x50, 0x89, 0xcf, 0x8d, 0x31, 0x74, 0x05, 0xad, 0x5a, 0x46, 0xe5,
	0x20, 0xd3, 0xd8, 0xcf, 0x99, 0x1e, 0x43, 0xcd, 0x9a, 0xa3, 0xfa, 0x02, 0xaa, 0x83, 0x11, 0xa1,
	0xc2, 0x67, 0xb0, 0x6e, 0x15, 0x0a, 0x6b, 0x59, 0x44, 0xb5, 0xa6, 0x99, 0x28, 0x2c, 0x66, 0x0f,
	0x36, 0xad, 0x72, 0x4c, 0x25, 0x0d, 0x98, 0xca, 0x1a, 0xd5, 0x12, 0x1e, 0xe8, 0x86, 0x99, 0x3c,
	0xcb, 0xe6, 0x30, 0xa7, 0x7f, 0x0c, 0xc4, 0xda, 0x48, 0xa6, 0x52, 0x69, 0x0b, 0xc0, 0x72, 0x91,
	0xc1, 0xc1, 0x09, 0xd4, 0xbe, 0x80, 0x35, 0xab, 0x1d, 0x44, 0x3e, 0x3f, 0xe7, 0x4c, 0xb6, 0x56,
	0xb6, 0x2b, 0xbb, 0x8d, 0xbd, 0xe3, 0xbb, 0x5d, 0xb9, 0x3b, 0xc7, 0x88, 0x7a, 0x6c, 0x41, 0x9d,
	0x46, 0x30, 0x31, 0xd6, 0x21, 0x1a, 0xb2, 0x44, 0x69, 0xef, 0x0e, 0x65, 0x94, 0xc6, 0xad, 0xaa,
	0x79, 0xb3, 0x5a, 0xe1, 0x4b, 0x2d, 0x23, 0x6d, 0x1d, 0x44, 0x3c, 0x92, 0x5c, 0x8d, 0x5a, 0x80,
	0xc1, 0x9e, 0x8f, 0x49, 0x00, 0xf5, 0xec, 0x76, 0x8b, 0x15, 0xb4, 0x86, 0x15, 0xf4, 0xb7, 0x77,
	0x5c, 0xf5, 0xbe, 0x81, 0xc4, 0x6a, 0x5a, 0xf3, 0xc6, 0x03, 0x1d, 0x60, 0x78, 0x9f, 0x33, 0xc7,
	0x5a, 0x37, 0x01, 0x86, 0x12, 0x3c, 0xd5, 0x5f, 0x61, 0x91, 0xb3, 0x1d, 0x7e, 0xe4, 0x06, 0x2c,
	0x49, 0xa8, 0xae, 0x02, 0x2c, 0x88, 0x05, 0x55, 0xac, 0xb5, 0x8a, 0x06, 0x0f, 0x55, 0xd6, 0xb1,
	0x47, 0xc7, 0x46, 0xa3, 0x6f, 0x15, 0xc8, 0x05, 0xec, 0x14, 0x01, 0x6c, 0xe3, 0x9e, 0xae, 0x95,
	0x8d, 0xf9, 0xdb, 0xe5, 0x98, 0xd2, 0xb4, 0xec, 0xa9, 0x7a, 0x79, 0x00, 0x8f, 0x8b, 0xbc, 0x99,
	0x4b, 0x13, 0x26, 0xce, 0x5d, 0x7d, 0x16, 0xcc, 0x6f, 0xad, 0xe1, 0x0d, 0xf6, 0xd1, 0x18, 0xc8,
	0x3a, 0xa9, 0xc7, 0xc4, 0xf9, 0x09, 0xaa, 0xcc, 0x6c, 0x39, 0xcd, 0xd9, 0x2d, 0xe7, 0x39, 0x3c,
	0x2c, 0xaa, 0x6a, 0x77, 0x8e, 0xdd, 0xb4, 0x8e, 0x36, 0x1f, 0x14, 0x14, 0xb4, 0x77, 0x73, 0x27,
	0x4d, 0xd9, 0xe2, 0x9f, 0x02, 0xb9, 0x2d, 0xb9, 0x66, 0xab, 0x9f, 0x0b, 0xb9, 0xed, 0xbf, 0x4a,
	0xb8, 0xd3, 0xdc, 0x38, 0x6f, 0xf1, 0x39, 0x42, 0xd2, 0xda, 0xc0, 0x42, 0x45, 0xef, 0x18, 0x43,
	0x85, 0x9e, 0x91, 0x37, 0xfe, 0x6c, 0x19, 0x09, 0x3a, 0xd0, 0xd9, 0x52, 0xef, 0xd3, 0x21, 0x29,
	0x7c, 0x5c, 0x5c, 0xea, 0xec, 0xd7, 0xe8, 0xfd, 0x5b, 0xc5, 0x42, 0x06, 0xda, 0x9b, 0xf1, 0x30,
	0x7d, 0x0a, 0x4d, 0x16, 0xd2, 0x81, 0xd0, 0x4f, 0xb3, 0xac, 0x76, 0x6f, 0x9a, 0x53, 0xb4, 0xf2,
	0xac, 0x26, 0x4f, 0xc7, 0xfb, 0x35, 0xb3, 0x07, 0xd3, 0xf1, 0x7e, 0x38, 0x09, 0xd0, 0x3e, 0x83,
	0x9d, 0xff, 0xed, 0x27, 0xd2, 0x84, 0xca, 0x5b, 0x36, 0xb2, 0xf5, 0x5c, 0x7f, 0x92, 0xfb, 0xb0,
	0x78, 0x41, 0x45, 0x9a, 0x35, 0x1b, 0x33, 0x78, 0x5e, 0xfe, 0xa2, 0xb4, 0xf3, 0x05, 0x34, 0x26,
	0x6b, 0x0e, 0x01, 0x58, 0x3a, 0x7b, 0xfd, 0xe2, 0x9b, 0xa3, 0xfd, 0xe6, 0x3d, 0xfd, 0xdd, 0xeb,
	0x77, 0xfb, 0x47, 0xfb, 0xcd, 0x12, 0x69, 0x00, 0x9c, 0x9c, 0xf6, 0x5d, 0x3b, 0x2e, 0xef, 0x1c,
	0x42, 0xad, 0x90, 0xf7, 0xd7, 0x7b, 0xa1, 0x11, 0xec, 0x1f, 0xba, 0x87, 0x27, 0x7d, 0xe7, 0xf7,
	0xcd, 0x92, 0x6e, 0x8e, 0xfd, 0xa3, 0xe3, 0x43, 0xa7, 0x59, 0xd6, 0x9f, 0xa7, 0xfd, 0x57, 0x87,
	0x4e, 0xb3, 0xd2, 0xfe, 0x0a, 0x1a, 0x93, 0xb7, 0xbf, 0xbc, 0x31, 0x96, 0x0a, 0x8d, 0xb1, 0x05,
	0xcb, 0x78, 0x21, 0x61, 0x12, 0xb7, 0xb0, 0xe2, 0x64, 0xc3, 0xf6, 0x3f, 0x2b, 0xd0, 0x98, 0x6c,
	0x7d, 0x33, 0x01, 0x7a, 0x45, 0x0f, 0xd4, 0xf6, 0xbe, 0xbc, 0x65, 0x5b, 0xed, 0x7c, 0xab, 0x41,
	0xac, 0x03, 0xc9, 0x77, 0xb0, 0x6c, 0xdf, 0xde, 0xf6, 0xe6, 0x77, 0x47, 0xd8, 0x0c, 0x4d, 0x9f,
	0x97, 0xa0, 0x03, 0x26, 0x6c, 0x27, 0x34, 0x03, 0xf2, 0x09, 0x34, 0xbc, 0x37, 0xcc, 0x7b, 0x3b,
	0x88, 0xae, 0x5c, 0x33, 0x6d, 0x3a, 0xe0, 0x6a, 0x26, 0xfd, 0x06, 0xd5, 0xb6, 0xa1, 0xe6, 0xb3,
	0xc4, 0x93, 0x3c, 0xce, 0x5f, 0x49, 0x55, 0xa7, 0x28, 0x6a, 0x47, 0xb0, 0x88, 0x84, 0xe4, 0x3e,
	0x2c, 0x0c, 0x2e, 0xa8, 0x30, 0xcf, 0xed, 0x57, 0xf7, 0x1c, 0x1c, 0x91, 0x2d, 0xa8, 0xfa, 0xfa,
	0xe9, 0x1f, 0xa6, 0x42, 0x18, 0x77, 0xbf, 0xba, 0xe7, 0xac, 0x68, 0xd1, 0x49, 0x2a, 0x84, 0x36,
	0xd2, 0xdf, 0xb8, 0xe5, 0x92, 0x36, 0xd2, 0x23, 0x2d, 0x4d, 0xb4, 0x14, 0x57, 0xac, 0xa5, 0x7a,
	0xf4, 0x62, 0x11, 0x2a, 0xfa, 0x67, 0x0b, 0x1e, 0x45, 0x72, 0xd8, 0xc9, 0x1c, 0xd3, 0xd1, 0x8e,
	0xe9, 0xd0, 0x98, 0x77, 0xd0, 0x31, 0x83, 0x25, 0xfc, 0x87, 0xf6, 0xf3, 0xff, 0x06, 0x00, 0x00,
	0xff, 0xff, 0x4c, 0x7b, 0x5e, 0x59, 0xe1, 0x15, 0x00, 0x00,
}
